POST https://testdeployment-yodj.onrender.com/api/blogs
Content-Type: application/json
Authorization: Bearer {token}

{
    "title": "test rest part5",
    "author": "cz224",
    "url" : "https://www.google.com"
}