POST https://testdeployment-yodj.onrender.com/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN6MjI0IiwiaWQiOiI2N2RjMmIyYTQ2OTI1ZWJkMjZlMjQ0ZjAiLCJpYXQiOjE3NDI5MTY3NTEsImV4cCI6MTc0MjkyMDM1MX0.DCt8uJk2DP_9zwq8fUdDDoGjRWL5WjNdMaZ7ccITnFs

{
    "title": "test rest part5",
    "author": "cz224",
    "url" : "https://www.google.com"
}