DELETE http://localhost:3001/api/blogs/67cf20aaf0e59493c821256a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2N2NiMWU3ZGE2MzA4ZmY2Njc5YjIyMjkiLCJpYXQiOjE3NDE3NzY3NjgsImV4cCI6MTc0MTc4MDM2OH0.tM78Cl7rYWwGDNazruOH856cQQ1mcKd8pyGa10cVVDM