DELETE https://testdeployment-yodj.onrender.com/api/blogs/67e2cefb0a79c07a1f0082d8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN6MjI0IiwiaWQiOiI2N2RjMmIyYTQ2OTI1ZWJkMjZlMjQ0ZjAiLCJpYXQiOjE3NDM2OTQ2NjMsImV4cCI6MTc0MzY5ODI2M30.PGo1MH857Csp3_-nJIbyDlTjPzJlulPjPAPb8reEPRQ